# Generated by Django 3.1.2 on 2020-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='hello world'),
            preserve_default=False,
        ),
    ]
